# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7429750030f1eec0f6bf494b8c7faa7661a626cb2e60d66f5cfbd73053fb236d41a3d56145d8fe832a7f8a6ba33663e9c201f5f350c3a230abf143aec3a6b5c6

test:
  secret_key_base: 8bcb08a00f2bc5877e3053efe0c92e0001378ab4a6f92b60e07a4e1042634906b6f25f6bb35511abb7920a048c142a19087d658a6cb18c708438fee3d67346cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
